### ISSUE TITLE
Cannot install RazorSharp from NuGet

### ISSUE THREAD

**Issue by dropsonic** [Decimation/RazorSharp#1]
An attempt to install RazorSharp from NuGet to the .NET Framework 4.8-targeted project ends up with an error message:

> Error		Unable to resolve dependency 'NativeSharp'. Source(s) used: 'nuget.org'.

**Comment by Decimation** [comment]
My bad. I removed `NativeSharp` from NuGet. You might want to check out [NeoCore](https://github.com/Decimation/NeoCore), a more up-to-date .NET Core implementation for now. Otherwise, I'll fix the dependencies in an upcoming release.

**Comment by Decimation** [comment]
The latest `RazorSharp` commit already has the `NativeSharp` dependencies integrated, which is why I removed it from NuGet -- I just forgot to update the `RazorSharp` NuGet package accordingly. The latest `RazorSharp` NuGet package should be working now. Feel free to reopen the issue if that's not the case.
